### ISSUE TITLE
No implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by frowing** [teambox/viper-module-generator#3]
When I try to create a new module I get that error. 

```/Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/lib/vipergen/filemanager.rb:38:in `expand_path': no implicit conversion of nil into String (TypeError)
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/lib/vipergen/filemanager.rb:38:in `copy'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/lib/vipergen/generator.rb:20:in `generate_viper'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/lib/vipergen/viperthor.rb:12:in `generate'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/bin/vipergen:8:in `<top (required)>'
	from /Users/fran/.rvm/rubies/ruby-2.1.1/bin/vipergen:23:in `load'
	from /Users/fran/.rvm/rubies/ruby-2.1.1/bin/vipergen:23:in `<main>'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by pepibumur** [comment]
What command are you using @frowing ?

**Comment by frowing** [comment]
`vipergen generate PlaceDetailModule --path=~/Projects/VipergenTest`

`ruby -v` shows `ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]`. I'm on Mavericks. Any other info you might need?

**Comment by pepibumur** [comment]
Does the VipergenTest folder exist @frowing ??

**Comment by frowing** [comment]
Yes, it does :)

**Comment by pepibumur** [comment]
This gem is outdated. Use this one @frowing https://github.com/pepibumur/viper-module-generator

**Comment by frowing** [comment]
Cool thank you!
